# Generated by Django 4.1.2 on 2022-12-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_order_user_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order_user',
            name='date',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='order_user',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
