# Generated by Django 4.1.2 on 2022-12-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_remove_order_date_order_user_date_order_user_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_user',
            name='date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
